---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En un enlace absoluto la URL puede estar incompleta.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El enlace que apunta a `/series/estreno/2018` es un enlace relativo.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El enlace que apunta a `https://netfix.io/series/estreno/2018` es un enlace
    relativo.
  checked: false
name: Absolutamente relativo
