---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: En un enlace absoluto la URL puede estar incompleta.
  checked: false
- value: El enlace que apunta a /series/estreno/2018 es un enlace relativo.
  checked: true
- value: El enlace que apunta a https://netfix.io/series/estreno/2018 es un enlace
    relativo.
  checked: false
name: Absolutamente relativo
